language: node_js
node_js:
  - "8"
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
script:
  - npm install
  - npm run build
  - npm run coverage
notifications:
  irc:
    channels:
      - "chat.freenode.net#pcxdbg"
    nick: pcxdbg-ci
    template:
      - "#%{build_number} on %{branch}: %{message}"
      - "Commit by %{author}: %{commit_message}"
      - "Change: %{compare_url}"
      - "Build: %{build_url}"
