version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - run:
          name: 'Version check'
          command: |
            node --version
            npm --version
      - checkout
      - run:
          name: 'Build'
          command: |
            npm install
            npm run build
      - run:
          name: 'Unit tests'
          command: npm run coverage
